# -*- coding: utf-8 -*-
"""Question 7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Iw0EOjhEjx1gvpwl9tGTN_wYtavDaLRf

Stage: Not stage-based — this is an infinite horizon problem solved via value iteration

State (s): The age of the bulbs in years, s = 1, 2, 3, 4, 5, 6

Action (x): At each year, decide:

x = R (Replace): Replace all 5000 bulbs now, reset age to 0

x = K (Keep): Keep bulbs for another year, age increases by 1


Variables:

Number of bulbs: 5,000

Bulb lifespan: 6 years (must replace by year 6)

Cost per bulb at replacement year k: $20, $16, $17, $21, $23, $19

Discount factor: α = 0.95

Contribution Function (total cost):

C(k) = 5000 × cost_per_bulb(k)

Value Iteration Recursion:

V(s) = min { C(s) + α × V(0),   α × V(s+1) }

Where:

First term = Replace now at age s: pay cost, reset to age 0

Second term = Wait one more year (only valid if s < 6)

At s = 6: must replace (bulb lifespan exceeded)

Terminal Condition:

V(6) = C(6) + α × V(0) — forced replacement at year 6
"""

import pandas as pd
import numpy as np

# ── Problem Parameters ───────────────────────────────────────────────────────
num_bulbs        = 5000
discount         = 0.95
max_age          = 6

# Cost per bulb at replacement year k (k=1..6)
cost_per_bulb    = {1: 20, 2: 16, 3: 17, 4: 21, 5: 23, 6: 19}

# Total replacement cost at age k
total_cost       = {k: num_bulbs * cost_per_bulb[k] for k in range(1, max_age + 1)}

# ── Value Iteration ───────────────────────────────────────────────────────────
# V[s] = min discounted cost from state s (age s years)
# states: 1, 2, 3, 4, 5, 6
# s=0 means just replaced (start of new cycle)

tol        = 1e-6       # convergence tolerance
max_iter   = 10000
V          = {s: 0.0 for s in range(0, max_age + 1)}   # initialise all to 0
policy     = {s: 'R' for s in range(1, max_age + 1)}

print("=" * 70)
print("       LIGHT BULB REPLACEMENT — VALUE ITERATION")
print("=" * 70)
print(f"\n  Bulbs: {num_bulbs:,}   |   Discount factor: {discount}   |   Max age: {max_age} years")
print(f"\n  Total replacement costs:")
for k in range(1, max_age + 1):
    print(f"    Year {k}: ${total_cost[k]:,.0f}  (${cost_per_bulb[k]}/bulb)")

iteration_log = []

for iteration in range(1, max_iter + 1):
    V_new    = {}
    policy   = {}
    max_diff = 0.0

    # V[0] = value of being in state 0 (just replaced, age=0)
    # From age 0, bulbs run for 1 year and become age 1
    # V[0] is implicitly defined through the cycle
    # We solve for ages 1..6

    for s in range(1, max_age + 1):

        # Option 1: REPLACE at age s
        cost_replace = total_cost[s] + discount * V.get(0, 0)

        # Option 2: KEEP (only valid if s < max_age)
        if s < max_age:
            cost_keep = discount * V.get(s + 1, 0)
        else:
            cost_keep = float('inf')   # must replace at age 6

        if cost_replace <= cost_keep:
            V_new[s]  = cost_replace
            policy[s] = 'Replace'
        else:
            V_new[s]  = cost_keep
            policy[s] = 'Keep'

    # Update V[0]: value at age 0 = value at age 1 discounted by 1 year
    # (after replacing, bulbs immediately become age 1 next year)
    V_new[0] = discount * V_new.get(1, 0)

    # Check convergence
    for s in range(0, max_age + 1):
        diff     = abs(V_new.get(s, 0) - V.get(s, 0))
        max_diff = max(max_diff, diff)

    # Log every 10 iterations + first 5
    if iteration <= 5 or iteration % 10 == 0:
        iteration_log.append({
            "Iteration" : iteration,
            "V(1)"      : round(V_new.get(1, 0), 4),
            "V(2)"      : round(V_new.get(2, 0), 4),
            "V(3)"      : round(V_new.get(3, 0), 4),
            "V(4)"      : round(V_new.get(4, 0), 4),
            "V(5)"      : round(V_new.get(5, 0), 4),
            "V(6)"      : round(V_new.get(6, 0), 4),
            "Max Diff"  : round(max_diff, 6)
        })

    V = V_new

    if max_diff < tol:
        print(f"\n  ✓ Converged after {iteration} iterations (tolerance={tol})\n")
        break

# ── Print iteration log ───────────────────────────────────────────────────────
print("  Iteration Log (selected):")
df_log = pd.DataFrame(iteration_log)
print(df_log.to_string(index=False))

# ── Final Results ─────────────────────────────────────────────────────────────
print("\n")
print("=" * 70)
print("  FINAL VALUE FUNCTION & OPTIMAL POLICY")
print("=" * 70)
rows = []
for s in range(1, max_age + 1):
    replace_cost = total_cost[s] + discount * V.get(0, 0)
    keep_cost    = discount * V.get(s + 1, 0) if s < max_age else float('inf')
    rows.append({
        "Bulb Age (yrs)"     : s,
        "V(s) Converged"     : round(V[s], 2),
        "Cost if Replace"    : round(replace_cost, 2),
        "Cost if Keep"       : round(keep_cost, 2) if keep_cost != float('inf') else "∞ (must replace)",
        "Optimal Action"     : policy[s]
    })

df = pd.DataFrame(rows)
print(df.to_string(index=False))

# ── Optimal replacement year ──────────────────────────────────────────────────
replace_ages = [s for s in range(1, max_age + 1) if policy[s] == 'Replace']
keep_ages    = [s for s in range(1, max_age + 1) if policy[s] == 'Keep']

print("\n")
print("=" * 70)
print("  SUMMARY")
print("=" * 70)
print(f"  Keep bulbs at ages : {keep_ages}")
print(f"  Replace at ages    : {replace_ages}")
optimal = min(replace_ages)
print(f"\n  ➤ Optimal regeneration policy: Replace ALL bulbs every {optimal} year(s)")
print(f"    i.e. always replace when bulbs reach age {optimal}")
print(f"\n  ➤ Optimal total replacement cost per cycle: ${total_cost[optimal]:,.0f}")
print(f"    (${cost_per_bulb[optimal]}/bulb × {num_bulbs:,} bulbs)")
print("=" * 70)

